[tool.poetry]
name = "django-templates-boilerplate"
version = "0.1.0"
description = ""
authors = ["Almaz Ilaletdinov <a.ilaletdinov@yandex.ru>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^4.0.4"
pytest = "^7.1.2"
djangorestframework = "^3.13.1"
djangorestframework-simplejwt = "^5.1.0"
drf-yasg = "^1.20.0"
ipython = "^8.3.0"
isort = "^5.10.1"
pendulum = "^2.1.2"
pytest-django = "^4.5.2"
django-split-settings = "^1.1.0"
django-environ = "^0.8.1"
django-debug-toolbar = "^3.4.0"
Pillow = "^9.1.0"

[tool.poetry.dev-dependencies]
beautifulsoup4 = "^4.11.1"
mixer = "^7.2.2"
lxml = "^4.8.0"
flake8 = "^4.0.1"
flake8-commas = "^2.1.0"
flake8-eradicate = "^1.2.1"
flake8-print = "^5.0.0"
pytest-freezegun = "^0.4.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
